name: Caching Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
	  node-version: 18
	  cache: 'npm'
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v4
        with:
	  node-version: 18
	  cache: 'npm'
      - run: npm ci

